appname: "instatweets"

session: "YAML"

plugins:
    "Auth::Twitter":
        consumer_key:       "secret"
        consumer_secret:    "secret"
        callback_url:       "http://localhost:3000/auth/twitter/callback"
